### PR TITLE
feat(module): cjs and amd module support

### LINKED ISSUE #83: Using c3-angular with require.js - problem!!
Hello, I am introducing require.js modularisation in my app, which uses c3-angular.

I get an error `c3 is not defined` which puzzles me a lot, because I have specified that c3-angular depends on c3.

Here are a couple of my requirejs shims for c3-angular. Have you got any experience with this sort issues?

    'c3-angular' : { deps: ['angular','c3'] },
    'c3' : { deps: ['d3'], exports: 'c3' },   

One of the major reasons of trouble in this case is that all c3-angular code is minified.
An uncompressed version would help me enormously with analyzing this problem, and I am opening another issue just for that.

### PR DESCRIPTION
**Pull request by spiroid**
This simple modification makes it easy to use this lib with webpack.
Return module name as recommanded by angular developers with cjs modules

fixes #83

### CODE REVIEW

**Comment by jettro** [comment]
Hi, I did not know this web pack project yet. Will this also help with the support for requirejs?

**Comment by jettro** [comment]
Hmm, looking at the code, but it breaks the javascript objects in _main and tooltip. I don't like that. Must be another way to support this. Right?

**Comment by spiroid** [comment]
hi @jettro ,

For webpack, i was refering to the module bundler : http://webpack.github.io/docs/what-is-webpack.html. It is a useful tool that makes it possible to split your app into modules with their namespace, resources and assets (js, css, images, etc.) and use these modules in the browser.

It should help with requirejs support as requirejs is based on [AMD](https://github.com/amdjs/amdjs-api/wiki/AMD): http://requirejs.org/docs/whyamd.html. Maybe @marco-faustinelli or @pascalbaljet could test this on their projects ?

As for the code in main and tooltip, i tried to make it work with the project existing build tools.
Another solution would be to add 2 files 000-module-start and zzz-module-end, to preserve grunt concat processing order and avoid modifications in other files. What do you think ?

Thanks :)

**Comment by jettro** [comment]
HI @spiroid going to do some more reading, tough theory for a backend developer :-). I found this article useful. 
http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

I would like to have a plugin for grunt to do this easier. But cannot really find something yet.

**Comment by jettro** [comment]
Not going to fix this with grunt. Will only fix this if I move to web pack

**Pull request closed without merging**
