### PR TITLE
Implement zoomend and onbrush callback

### LINKED ISSUE #128: Implement zoomend and onbrush callback
I found in the C3 document, there are some callback functions for zoomend and subchart onbrush. Can you implement those features? http://c3js.org/reference.html#subchart-onbrush http://c3js.org/reference.html#zoom-onzoomend

Many thanks!

### PR DESCRIPTION
**Pull request by mumuxin**
This PR fixes #128 
Add the callback functions for the event of chart zoom-end and subchart on-brush
http://c3js.org/reference.html#subchart-onbrush 
http://c3js.org/reference.html#zoom-onzoomend 
I am doing a project with the c3-angular, could you help me add these new features into?
Many thanks

### CODE REVIEW

**Comment by jettro** [comment]
Hi, you have made changes to the generated file. The changes you have made should be in controller.js and c3chart-directive.js, this way I cannot merge it.

**Comment by mumuxin** [comment]
Hi, @jettro , I have made the changes in controller.js and c3chart-directive.js and roll back the changes in c3-angular.js

**Comment by polyrabbit** [comment]
Hi @jettro , is there anything wrong with this PR? I reached here via google, our team also needs this feature. Thanks!

**Comment by jettro** [comment]
Need to find time to check the PR, do the merge, create a release. Will do it as soon as possible.

**Comment by polyrabbit** [comment]
Many thanks for your great work!

**Comment by mumuxin** [comment]
Thank you! Jettro

**Pull request merged**
