### PR TITLE
Adds wrapper for transition duration

### PR DESCRIPTION
**Pull request by tamasgal**
Just a few lines of code to allow changing the transition-duration.

### CODE REVIEW

**Comment by miickel** [comment]
I'm looking to disable the animations all together, would love to see this merged. What do you say @tamasgal?

**Comment by tamasgal** [comment]
Well, this is already a pull request, so one of the admins has to decide it ; ) You can merge it in your own clone and simply use `transition.duration = 0` for now…

**Comment by miickel** [comment]
@tamasgal haha sorry, too much coffee yesterday :astonished:. I meant, what do you think about having this merged @jettro

**Comment by jettro** [comment]
I have to give a presentation tomorrow, than my work on a book I was
involved with is done, presentation is done. So I finally hope to have some
time to give it a good look and merge it in.

Would be nice to have a sample/demo in the examples folder to show that
what you have done works.

regards Jettro

On Wed, Nov 4, 2015 at 3:08 PM, Mickel <notifications@github.com> wrote:

> @tamasgal <https://github.com/tamasgal> haha sorry, too much coffee
> yesterday [image: :astonished:]. I meant, what do you think about having
> this merged @jettro <https://github.com/jettro>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jettro/c3-angular-directive/pull/70#issuecomment-153729881>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by jettro** [comment]
Hi @tamasgal looking at merging this, but I do not see yet what the big advantage is, you'd like to change the animation while the chart is already running, am I correct? Would like to create an example which shows what you want. Also made a lot of changes to the code that makes it not possible to auto merge this.

**Comment by jettro** [comment]
@miickel Disabling transitions is done by passing null, which does not work in the way it is currently implemented. Going to add an option to disable transitions.

**Comment by jettro** [comment]
Without a response I am going to revoke this pull requests. So much has changed that the pull request would not to be updated to the latest state first.

**Pull request closed without merging**
